### ISSUE TITLE
Add CloudFront support

### ISSUE THREAD

**Issue by rscottbailey** [brandond/stick#2]
I'm working in an environment where I want to front my bucket (on the consumer side) with a CloudFront distribution. (off topic: this is so I can implement basic authentication with an edge lambda)

At present, generated metadata is unusable because all URLs are absolute and are created using the bucket's FQDN, which isn't accessible. Some options:

1. Make URLs relative (so they are insensitive to the base URL of the repository)
2. Add `--url https://my-stupid-repo.com` switch that allows the URL to be overridden; I actually have implemented this and it's pretty straightforward -- but it's slightly annoying to have to specify both the bucket name and the FQDN on the command line
3. Add `--distribution XYZZYWHATEVER` switch (mutually exclusive with `--bucket`) that specifies the CloudFront distribution identifier (at which point stick can look up both the bucket name and the distribution FQDN)

Thanks for your responsiveness,
Scott

**Comment by brandond** [comment]
Does https://github.com/brandond/stick/commit/6df1a631902128fb39cdf153f31ec102fe6cfba7 do what you need?

**Comment by brandond** [comment]
This should also allow it to work with stuff like the new S3 Access Points feature where the bucket can have multiple aliases.

**Comment by brandond** [comment]
FYI, I was originally inspired to write stick after using https://github.com/novemberfiveco/s3pypi which was designed around using CloudFront. I wasn't quite happy with how it worked and wanted to change it in a few keys so I just started over from scratch.
